nbbuild.generateCopyExternals = false

task copyJavaFxLib(type: Copy) {
    from zipTree('external/lib-javafx-13.03-beta.nbm').files
    into file("$buildDir/external")
    include '**/javafx-2.2.4.jar'
}

task rejarJavaFxLib(type: Jar) {
    dependsOn(copyJavaFxLib)
    from zipTree("${buildDir}/external/javafx-2.2.4.jar")
    destinationDirectory = file("${buildDir}/libs")
    archiveFileName = 'javafx-2.2.4.jar'
}

artifacts {
    api(rejarJavaFxLib)
}

