/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.ide.testing.ui;

import org.openide.explorer.ExplorerManager;
import org.openide.windows.TopComponent;

/**
 *
 * @author lkishalmi
 */
@TopComponent.Description(
        preferredID = "testreport-viewer",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(
        mode = "output",
        openAtStartup = false,
        position = 1945
)
public class TestReportWindow extends TopComponent implements ExplorerManager.Provider {

    ExplorerManager manager = new ExplorerManager();
    
    /**
     * Creates new form TestReportPanel
     */
    public TestReportWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbActions = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        pbTestProgress = new javax.swing.JProgressBar();
        spTestTree = new javax.swing.JScrollPane();
        spTestOutput = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        tbActions.setFloatable(false);
        tbActions.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tbActions.setRollover(true);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(TestReportWindow.class, "TestReportWindow.jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbActions.add(jButton1);

        add(tbActions, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        pbTestProgress.setStringPainted(true);
        jPanel1.add(pbTestProgress, java.awt.BorderLayout.NORTH);
        jPanel1.add(spTestTree, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);
        jSplitPane1.setRightComponent(spTestOutput);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JProgressBar pbTestProgress;
    private javax.swing.JScrollPane spTestOutput;
    private javax.swing.JScrollPane spTestTree;
    private javax.swing.JToolBar tbActions;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return manager;
    }
}
